In [16]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from sklearn.preprocessing import StandardScaler
from keras.losses import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
sns.set_style('darkgrid')
plt.rcParams['figure.dpi'] = 108



In [43]:
dt = pd.read_csv("model_data/data.csv",sep ="\t")
test_dt =pd.read_csv("model_data/test_data.csv",sep ="\t")
# standard
scaler = StandardScaler()
scaler.fit(dt.drop('Real',axis =1))
ds = scaler.transform(dt.drop('Real',axis=1))
dt['Real'] =dt.apply(lambda x: 0 if x.Real ==-1 else 1, axis =1)


In [44]:
#ds =dt.drop('Real',axis=1)
print(ds)
y = dt.Real
print(y.tail())
test_dt = scaler.transform(test_dt)
print(test_dt)

[[-0.10263922 -0.29704977 -0.29111249 -0.1276681  -0.12989937]
 [-0.10424959 -0.3991067  -0.26039485         nan -0.14442995]
 [-0.10602947 -0.41368626 -0.26039485         nan -0.14442995]
 ...
 [-0.06966908 -0.3991067  -0.29111249         nan -0.13353201]
 [-0.07187274 -0.29218992 -0.27882544         nan -0.14442995]
 [-0.08348433  1.5934333  -0.28804073         nan -0.13716466]]
7950    1
7951    1
7952    0
7953    1
7954    0
Name: Real, dtype: int64
[[-0.10696178 -0.42826582 -0.2051031  -0.1276681  -0.13353201]
 [-0.10272398 -0.37966729 -0.26653838 -0.1276681  -0.13716466]
 [-0.09136665 -0.05405709 -0.24196427 -0.1276681  -0.1407973 ]
 ...
 [-0.10645325 -0.41368626 -0.28804073 -0.1276681  -0.13716466]
 [-0.10399532 -0.40882641 -0.28496897 -0.1276681  -0.13716466]
 [-0.08806116 -0.39424685 -0.28804073 -0.1276681  -0.13716466]]


In [46]:
poly =PolynomialFeatures(2)
ds=poly.fit_transform(ds)
test_dt = poly.fit_transform(test_dt)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(ds, y, test_size=0.2, random_state=1)
print("Training set has {} instances. Test set has {} instances.".format(X_train.shape[0], X_test.shape[0]))



Training set has 3164 instances. Test set has 791 instances.


In [21]:
from sklearn.linear_model import RidgeCV
ridgecv = RidgeCV(alphas=[0.01, 0.1, 0.5, 1, 3, 5, 7, 10, 20, 100])
ridgecv.fit(X_train, y_train)
ridgecv.alpha_ 

20.0

In [27]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=20)
ridge.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=3.71868e-20): result may not be accurate.
  overwrite_a=True).T


Ridge(alpha=20, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [28]:
print (ridge.coef_)
print (ridge.intercept_)


[ 0.00000000e+00  5.51995967e-06 -2.70912656e-04  1.48627232e-04
 -3.77000015e-01  4.53192563e-02  8.03176462e-12 -2.81569433e-10
  1.51025242e-08 -5.31938231e-06  1.06650508e-07  1.35387757e-07
  9.05055657e-08 -2.18478917e-08 -5.16721278e-07 -3.93050661e-08
 -3.39858822e-08 -7.97215263e-07  1.88185863e-04 -4.38065059e-02
 -2.20396538e-06]
1.2994418608236504


In [29]:
ridge.predict(X_test)

array([-2.10312785e-01,  9.29645027e-01,  9.23735491e-01, -2.11518698e-01,
        9.23941017e-01,  5.35898919e-01,  5.06500828e-01,  9.52720671e-01,
        9.21017758e-01,  9.53365864e-01,  1.54567296e-01,  9.12731463e-01,
        9.57910763e-01,  1.66911439e-01,  9.16740111e-01,  9.21795887e-01,
        9.23172522e-01,  9.01620497e-01,  9.44732017e-01, -2.32124932e-01,
        8.39970337e-01,  9.41897406e-01,  9.94088118e-01,  9.21623926e-01,
       -2.16796536e-01,  9.22508093e-01,  8.85895452e-01,  8.28682550e-02,
        1.69097280e-01, -5.81594547e-01,  9.32094943e-01,  1.67683666e-01,
        9.07468384e-01,  9.19459579e-01,  9.56856327e-01,  5.27629036e-01,
        9.44773261e-01,  1.25926280e-01,  9.22954643e-01,  9.29964188e-01,
        9.25705738e-01,  1.31276029e-01,  8.91729577e-02,  9.21435905e-01,
        9.75971093e-01,  9.22657596e-01,  1.02324865e+00,  9.33082507e-01,
        3.19962160e-02,  1.67519327e-01,  9.18045873e-01,  5.25229155e-01,
        9.19334656e-01, -

In [30]:
print(y_test)

2281    0
1128    1
719     1
3712    0
1882    1
       ..
1349    1
305     0
1448    0
439     0
713     1
Name: Real, Length: 791, dtype: int64


In [31]:
ridge.score(X_test, y_test)

0.8677263601943246

In [41]:
y_real_test = ridge.predict(test_dt)
print(y_real_test)

y_test_result = list(map(lambda x: 1 / (1 + math.exp(-x)),y_real_test))
print(y_test_result)
result = pd.read_csv('data/sample.csv',sep = ',')
print(result.head())
result['Predicted'] = y_test_result
result.to_csv('predictions/result3.csv',sep = ',',index =False)

[-0.20239967  0.16724811  0.52702078 ...  0.16853142  0.16811031
  0.16519819]
[0.4495721170074228, 0.5417148348495843, 0.6287879888897385, 0.6319860682986089, 0.5437325619907046, 0.44830115266354453, 0.6255946781722105, 0.5247786300888875, 0.5337433743821672, 0.5438764103396334, 0.5308933857512083, 0.5365544704645323, 0.6279379584315998, 0.5082005700021718, 0.5423884749750542, 0.6538509930127276, 0.6348947297619184, 0.4482895169972579, 0.5408022420463243, 0.6290182962125659, 0.3605139947781558, 0.6135568464950463, 0.5386035490160692, 0.44826273208504797, 0.6304349413851744, 0.541984810858881, 0.4541797956778623, 0.548398229754886, 0.5486409487414972, 0.5346799973001134, 0.44987805817269144, 0.6436494034028349, 0.5422729155929161, 0.5461483885415293, 0.6322366855731394, 0.5036355435429628, 0.48737746705805585, 0.6318795867010311, 0.6121842587583152, 0.6312511484309467, 0.5418142712405501, 0.6324053917207756, 0.6302737867127969, 0.633002032245659, 0.5392896809957233, 0.5422992077079783,

In [10]:
from sklearn.linear_model import Ridge
X_train = X_train/ 100.0
X_test = X_test / 100.0

In [11]:
degrees = list(range(12))
models = list()
train_mses = list()
test_mses = list()

X_grid = np.linspace(min(X_train.min(), X_test.min()),
                     max(X_train.max(), X_test.max()), num=1001)

plt.figure(figsize=(20,16))
for i, degree in enumerate(degrees):
    plt.subplot(len(degrees)//2, 2, i+1)

    # Transform features
    poly = PolynomialFeatures(degree=degree)
    Phi_train, Phi_test = poly.fit_transform(X_train), poly.fit_transform(X_test)
    Phi_grid = poly.fit_transform(X_grid[:,np.newaxis])

    # Fit model
    lr_poly = Ridge(alpha = 0.002).fit(Phi_train, y_train)
    models.append(lr_poly)
    
    # Evaluate
    train_mse = mean_squared_error(lr_poly.predict(Phi_train), y_train)
    train_mses.append(train_mse)
    test_mse = mean_squared_error(lr_poly.predict(Phi_test), y_test)
    test_mses.append(test_mse)

    plt.plot(X_grid, lr_poly.predict(Phi_grid), 'k', label='Prediction')
    plt.scatter(X_train, y_train, color='b', marker='.', label='Train')
    #plt.scatter(X_test_s, y_test, color='r', marker='.', label='Test')
    plt.title('Degree {} | Train MSE {:.3f}'.format(degree, train_mse))
    plt.legend()

plt.suptitle('Polynomial ridge regression for different polynomial degrees', y=1.05, fontsize=32)
plt.tight_layout()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().