In [20]:
# General libraries
import pandas as pd
import numpy as np
from collections import defaultdict
import random
from random import randrange
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import CategoricalNB

In [21]:
dataset = pd.read_csv("../data_models/dataset.csv", sep='\t')

In [22]:
# Shuffle the data set
dataset = dataset.sample(frac=1).reset_index(drop=True)
# Filling NaN values with zeros. Not sure if it is correct.
dataset['Com_Followings_Ratio'] = dataset['Com_Followings_Ratio'].fillna(0)

In [23]:
msk = np.random.rand(len(dataset)) < 0.8

Y = dataset['Real']
X = dataset.drop(columns=['Real','Source','Sink'])

# Normalization
#X = (X-X.min())/(X.max()-X.min())

X_train = X[msk]
X_test = X[~msk]
Y_train = Y[msk]
Y_test = Y[~msk]

In [24]:
model = CategoricalNB()
model.fit(X_train, Y_train)
predict = model.predict(X_test)

In [25]:
# accuracy 
print (classification_report(Y_test, predict,digits = 6))
print (confusion_matrix(Y_test, predict))
print (accuracy_score(Y_test, predict))

              precision    recall  f1-score   support

           0   0.755507  0.893229  0.818616       768
           1   0.869634  0.711313  0.782546       769

    accuracy                       0.802212      1537
   macro avg   0.812570  0.802271  0.800581      1537
weighted avg   0.812608  0.802212  0.800569      1537

[[686  82]
 [222 547]]
0.8022121014964216


In [26]:
print(predict)

[0 1 0 ... 1 0 1]


In [27]:
predict_proba = model.predict_proba(X_test)
print(predict_proba)

[[0.69769492 0.30230508]
 [0.17947272 0.82052728]
 [0.9499564  0.0500436 ]
 ...
 [0.30601662 0.69398338]
 [0.56718804 0.43281196]
 [0.39735756 0.60264244]]


In [28]:
# Reading test data
test_data = pd.read_csv("../data_models/test_data.csv", sep='\t')
test_data['Com_Followings_Ratio'] = test_data['Com_Followings_Ratio'].fillna(0)
# Normalization
#test_data = (test_data-test_data.min())/(test_data.max()-test_data.min())
test_data = test_data.drop(columns=['Sink','Source'])

In [18]:
test_data.shape

(2000, 6)

In [19]:
X_test.shape

(1603, 6)

In [29]:
predict_test = model.predict(test_data)
predict_test 

IndexError: index 4353 is out of bounds for axis 1 with size 1415