In [29]:
# General libraries
import pandas as pd
import numpy as np
from collections import defaultdict
import random
from random import randrange
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import roc_auc_score


In [3]:
dataset = pd.read_csv("../data_models/dataset7.csv", sep='\t')

In [7]:
# Shuffle the data set
dataset = dataset.sample(frac=1).reset_index(drop=True)
# Filling NaN values with zeros. Not sure if it is correct.
dataset['Com_Followings_Ratio'] = dataset['Com_Followings_Ratio'].fillna(0)
dataset = dataset.replace([np.inf],1000)

In [8]:
dataset.isna().any()

Source                     False
Sink                       False
Source_Followings          False
Source_Followers           False
Sink_Followers             False
Distance                   False
Real                       False
Common_Followings          False
Com_Followings_Ratio       False
Followers_Ratio            False
Indirect_Followings        False
Inv_Indirect_Followings    False
Source_friends_num         False
friends_cycle_num          False
SourceFollowersToSink      False
dtype: bool

In [11]:
msk = np.random.rand(len(dataset)) < 0.8

Y = dataset['Real']
X = dataset.drop(columns=['Real','Source','Sink'])

# Normalization
#X = (X-X.min())/(X.max()-X.min())

X_train = X[msk]
X_test = X[~msk]
Y_train = Y[msk]
Y_test = Y[~msk]

In [12]:
model = CategoricalNB()
model.fit(X_train, Y_train)
predict = model.predict(X_test)

In [13]:
# accuracy 
print (classification_report(Y_test, predict,digits = 6))
print (confusion_matrix(Y_test, predict))
print (accuracy_score(Y_test, predict))

              precision    recall  f1-score   support

           0   1.000000  1.000000  1.000000       785
           1   1.000000  1.000000  1.000000       802

    accuracy                       1.000000      1587
   macro avg   1.000000  1.000000  1.000000      1587
weighted avg   1.000000  1.000000  1.000000      1587

[[785   0]
 [  0 802]]
1.0


In [30]:
print('Accuracy: ' + "{:.4f}".format(accuracy_score(Y_test, predict)))
print('AUC: ' + "{:.4f}".format(roc_auc_score(Y_test, predict)))

Accuracy: 1.0000
AUC: 1.0000


In [14]:
print(predict)

[0 1 1 ... 1 0 0]


In [15]:
predict_proba = model.predict_proba(X_test)
print(predict_proba)

[[9.99943214e-01 5.67856130e-05]
 [4.54148548e-04 9.99545851e-01]
 [3.14060313e-04 9.99685940e-01]
 ...
 [1.38892946e-05 9.99986111e-01]
 [9.99811639e-01 1.88360926e-04]
 [9.99994019e-01 5.98106594e-06]]


In [22]:
# Reading test data
test_data = pd.read_csv("../data_generated/test_data.csv", sep='\t')
test_data['Com_Followings_Ratio'] = test_data['Com_Followings_Ratio'].fillna(0)
test_data = test_data.replace([np.inf],1000)
# Normalization
#test_data = (test_data-test_data.min())/(test_data.max()-test_data.min())
test_data = test_data.drop(columns=['Sink','Source'])

In [17]:
test_data.shape

(2000, 12)

In [23]:
test_data.isna().any()

Source_Followings          False
Source_Followers           False
Sink_Followers             False
Distance                   False
Common_Followings          False
Com_Followings_Ratio       False
Followers_Ratio            False
Indirect_Followings        False
Inv_Indirect_Followings    False
Source_friends_num         False
friends_cycle_num          False
SourceFollowersToSink      False
dtype: bool

In [24]:
test_data.isin([np.inf]).any()

Source_Followings          False
Source_Followers           False
Sink_Followers             False
Distance                   False
Common_Followings          False
Com_Followings_Ratio       False
Followers_Ratio            False
Indirect_Followings        False
Inv_Indirect_Followings    False
Source_friends_num         False
friends_cycle_num          False
SourceFollowersToSink      False
dtype: bool

In [26]:
test_data.shape

(2000, 12)

In [31]:
predict_test = model.predict(test_data)
predict_test 

IndexError: index 1000 is out of bounds for axis 1 with size 5